apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-service
  namespace: todo-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: todo-service
  template:
    metadata:
      labels:
        app: todo-service
    spec:
      containers:
      - name: todo
        image: sandali95/todo-service:1.3
        ports:
        - containerPort: 3001
        env:
        - name: MONGO_URI
          valueFrom:
            secretKeyRef:
              name: mongo-secret
              key: MONGO_URI
        - name: PORT
          value: "3001"
        - name: DB_TYPE
          value: "mongodb"
        - name: DB_HOST
          value: "mongo"
        - name: DB_PORT
          value: "27017"
        - name: DB_NAME
          value: "todoapp"
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: mongo-secret
              key: MONGO_INITDB_ROOT_USERNAME
        - name: DB_PASS
          valueFrom:
            secretKeyRef:
              name: mongo-secret
              key: MONGO_INITDB_ROOT_PASSWORD
---
apiVersion: v1
kind: Service
metadata:
  name: todo-service
  namespace: todo-app
spec:
  type: LoadBalancer
  selector:
    app: todo-service
  ports:
  - name: http
    port: 3001               # external port on LB
    targetPort: 3001 
